# Generated by Django 2.0 on 2021-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notified',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
